apiVersion: v2
name: bullseye
description: A Helm chart for Geoguessr Bullseye Game Tracker
type: application
version: 0.1.8
appVersion: "1.0.0"
icon: https://images.squarespace-cdn.com/content/v1/636e083394b53b69d6c3e3fb/727307c8-bdd7-40c9-945b-8adfee1cb488/logo-pin.png
