global:
  imagePullSecrets: []

backend:
  image:
    repository: docker.io/wakalou/bullseye-backend
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  env:
    # DATABASE_URL: "postgres://..." # Override this in production if using Postgres
    # API_KEY: "your-secret-key"
  persistence:
    enabled: true
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 1Gi

frontend:
  image:
    repository: docker.io/wakalou/bullseye-frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: "traefik" # Default for k3s
  annotations: {}
    # kubernetes.io/ingress.class: traefik
  hosts:
    - host: bullseye.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

  basicAuth:
    enabled: true
    # user: admin, password: bullseye (generated via htpasswd -nb admin bullseye)
    # You SHOULD change this.
    htpasswd: "admin:$apr1$vLB3gJZo$cUr9geptxXkg2KnOL.kL7."
