{{- if .Values.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bullseye.fullname" . }}-basic-auth
  labels:
    {{- include "bullseye.labels" . | nindent 4 }}
data:
  users: {{ .Values.ingress.basicAuth.htpasswd | b64enc | quote }}
{{- end }}
